export enum PermissionEnum{
    ADMINISTRATOR_PERMISSION = 'ADMINISTRATOR_PERMISSION',
	STUDENT_PERMISSION = 'STUDENT_PERMISSION',
	NASTAVNIK_PERMISSION = 'NASTAVNIK_PERMISSION',
	KORISNIK_PERMISSION = 'KORISNIK_PERMISSION',
	STUDENTSKASLUZBA_PERMISSION = 'STUDENTSKASLUZBA_PERMISSION'
}